### ISSUE TITLE
Validate if/else with scripting element checks

### ISSUE THREAD

**Issue by buggtb** [spicule-kythera/seleniumscripter#31]
Lets pretend the runScript function returned an element, that element might be collected from a wait step.

I'd like to be able to do something like this:

```yaml
    g:
      operation: if
      condition:
        - operation: wait
          selector: xpath
          name: "//*[(contains(@class, 'btn') and text() = 'Coverage details') or @data-ng-show='noResultsFound']"
          timeout: 90
          asyncwait: false
        - validation: text == "Coverage details"
```

where text or another element prodding function allowed us to check stuff, Perhaps check id's, css classes, probably not much more.

But in the example above, I've defined both the true and the false response for that optum page, this means that we'll move on as soon as either element becomes visible rather than waiting for the timeout, but then we need to figure out which element is visible was it the one that drops us into the if block or the one that drops us into the else block.
